### ISSUE TITLE
 Update the user manual

### ISSUE THREAD

**Issue by jcbrand** [conversejs/user-manual#1]
Original ticket here: https://github.com/conversejs/converse.js/issues/1383

The [user manual](https://conversejs.org/docs/html/manual.html) is very old and incomplete.

# Tasks for this ticket:

* [ ] Replace all screenshots with modern versions.
* [ ] Also create similar screenshots for Converse in fullscreen [view_mode](https://conversejs.org/docs/html/configuration.html#view-mode)

##  Expanding the manual with more information (WIP)

* [ ] OMEMO Encryption
* [ ] OMEMO Encryption in a groupchat
* [ ] How to verify OMEMO fingerprints

# Technical information

The user manual is in It's in `./docs/source/manual.rst` in the Converse repo. 
See: https://github.com/conversejs/converse.js/blob/master/docs/source/manual.rst

The manual is written in [RestructuredText](http://docutils.sourceforge.net/docs/user/rst/quickstart.html) and generated with [Sphinx](http://www.sphinx-doc.org/en/stable/)

Sphinx uses Python, so you'll need to set up a Python virtual environment with Buildout to manage dependencies.

Follow the instructions here: https://github.com/conversejs/converse.js/blob/master/docs/source/documentation.rst

**Comment by lyabs243** [comment]
@jcbrand Okay understand

**Comment by lyabs243** [comment]
@jcbrand  is it necessary to use "sphinx-quickstart" to update an existing sphinx  reStructuredText?

**Comment by jcbrand** [comment]
> is it necessary to use "sphinx-quickstart" to update an existing sphinx reStructuredText?

No, it's not necessary.

YOu can just edit the index.rst file and then run `make html`.

**Comment by lyabs243** [comment]
@jcbrand i have the following error when i try to build
```Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "c:\users\lyabs\appdata\local\programs\python\python37\lib\site-packages\sphinx\config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "c:\users\lyabs\appdata\local\programs\python\python37\lib\site-packages\sphinx\util\pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "C:\wamp\www\user-manual\source\conf.py", line 94, in <module>
    import sphinx_bootstrap_theme
```

**Comment by jcbrand** [comment]
@lyabs243: Let's discuss this in the chatroom.

**Comment by marclaporte** [comment]
For the record, documentation is now here: https://conversejs.org/docs/html/index.html
